---
title: "Integrating ecology with knowledge systems"
format: html
editor: visual
---

# Introduction/Outline

## Overview

-   The philosophy of open science has emerged in the last XX years as a cornerstone of modern research (Allen, PloS Bio 2019).
    In its essence, open science focuses on the reproducibility of research, providing accessible research resources (code, data, materials, etc) and published documents (e.g., open source articles) that allow for replication and reanalysis of existing studies (Table 1: Allen).
    <!--# In addition to facilitating reanalysis, open science also allows analysis of an existing dataset using alternative methods. Mention of this provides a nice segue to the next bullet point, i.e., building on previous work. -->

-   While open science's focus on reproducibility is critical for developing robust foundations for new studies to build upon, the core philosophy of open science is to indirectly enable new research by solidifying the veracity of previous research.

-   However, science is ultimately about generating new knowledge.
    We propose the concept of "open systems" as a useful, but little used framework in ecology and environmental science to enable mature research systems to reproduce existing knowledge and generate new knowledge.
    <!--# "Open system" is a somewhat ambiguous descriptor because it has many meanings in ecology. E.g., an open ecosystem is one that doesn't have distinct boundaries, etc. A less ambiguous term would be "open information system" -->

-   We define an "open system" practically in terms of the goal that it seeks to achieve.
    In an "open system", someone unfamiliar with the system (e.g., ) can interface with a conceptual model of the system to ask and answer a new question that the "creators" of open system haven't thought of yet, given the infrastructure (data, research, etc.) that already exist for the system.
    <!--# I would suggest a broader definition: an open information system describes an understanding of a system at a given point in time. This system can be used by those working in the system as a refernce for developing new research questions, or by someone unfamiliar with the system to address new questions. This broader phrasing gets around the question of why anyone would want to put time into developing an open information system when it will only be used by "outsiders".  -->\

-   The concept of "open systems" are not new in their philosophy.
    The broad field of "knowledge systems" and "information ecology" have thought deeply about how to integrate and synthesize multiple streams of ecological and environmental knowledge.

-   More here on "knowledge systems" background.
    But not too much!

-   Our goal in this paper is one of practitioners and not philosophers.
    As researchers in a system that we have cumulatively worked in for X years, we are concerned with X questions.

    -   What are the benefits and challenges of trying to make a mature ecological research system into an open system?\
    -   What are the steps needed to transform our system into an open system that can produce generative research without our constant input?
    -   \[Other questions\]

-   We first discuss what we see as the benefits and challenges of developing open systems more generally in ecological systems.

    We then focus in on our ecological research system and discuss three components that we believe can transform our system from a reproducible system focused on open science to an open system ripe for asking generative ecological questions: i) data availability ii) a conceptual model and iii) access support \[or something about support...knowledge can't be completely extracted away from system experts\].
    Overall, this paper provides a case study for the benefits and challenges of creating open systems in mature ecological research systems.
    \[Probably want to bring in conceptual models a bit more in the intro\]

## Benefits of open systems

-   List of benefits of open systems

1.  Access and equity:
    1.  Not everyone has equal capacity to collect data in all systems. Providing open data and conceptual models can remove barriers to stimulate new discoveries within ecological systems.
2.  Scientific progress
    1.  Efficiency: Open systems provide a way for new researchers to enter a system and ask and answer new questions efficiently. Importantly, this takes the burden off the system's researchers to constantly bring new folks "up to speed".
    2.  Allows research systems to exist somewhat independently of system-specific researchers. Improves continuity of science across generations of researchers.
    3.  More accessibility = new research = more problems solved (and more problems raised...)

## Challenges of open systems

-   List of the challenges of open systems

    1.  Encapsulating multiple forms of knowledge into a conceptual model that can be used and understood by non system experts.
        1.  A huge literature on how to do this and challenges with this approach – knowledge systems
    2.  Initial and continuing investments in building an open system
        1.  Very few incentives to build and maintain open systems beyond LTER-type funding mechanisms
    3.  The reticence of letting "non-experts" work in a system
        1.  Fear of getting "scooped"
    4.  The impossibility of replacing the system "expert" with a conceptual model. We can't and shouldn't be completely abstracting system because not all knowledge can be captured in a conceptual model.

------------------------------------------------------------------------

## Mark's thoughts

**Goal of open systems**: Someone unfamiliar with a system can take a codified "open system" and they can *ask* and *answer* a new question that the creators of the open system haven't thought of yet, given the infrastructure (data, products, etc.) that already exist for the system.
<!--# Broaden this to clarify that an open system is also central to those who are intimately familar with a system as a way of summarizing the current state of knowledge, a summary that will often be important for developing new research directions.  -->

-   Note that *asking* and *answering* questions with *existing* infrastructure are all key here.

    -   *Asking* on its own is not unique to an open system.
        But an open system facilitates neophytes of the system to ask novel, important questions quickly.

    -   *Answering* with *existing infrastructure*: Science proceeds by people building on each others ideas.
        The open systems facilitate this by allowing new researchers to use existing infrastructure to answer questions that have been facilitated by the open system.

        -   I specifically am thinking about data, but this could apply to other infrastructure such as personal networks...for example, contrast Sam Lapp working with Tom and Roland in Sierras compared to trying to work with unnamed Panamamian amphibian disease researcher where infrastructure is not open.

        -   Metadata and reproducibility play a big role in allowing new researchers to answer questions with existing data/infrastructure, while the conceptual model allows new researchers to formulate and contextualized questions.

<!-- -->

-   Constrast this with "open science" and "reproducible science": Here, the a goal is that someone can reproduce an analysis you have already done.
    They are asking and answering a question you have already asked.

-   "Open science" is a critical foundation for "open systems".
    You can't have open systems without open science.
    But the focus of open systems is on *generative* science in addition to reproducible science.

-   Conceptual models are key for asking new questions.
    Open science is key for being able to answer those questions.
    Conceptual model + open science = open systems.
    A simplification, but a place to start.

### Some challenges and thoughts on open systems

-   *Conjecture*: Maturation of a system is critical for open science to apply.
    Open science it really not all that useful if there are too many unknowns in the system, because the "new" scientist doesn't gain much from a conceptual synthesis of the system.
    When does a system become mature enough for an open systems approach to apply \[specifically, generative research can be done from existing data, metadata, and a conceptual model of the system\]?

-   Open systems requires additional commitments and efforts from system specialists.
    In addition to sharing data and metadata, they also need to put effort into synthesis beyond their published work, developing a conceptual model that is accessible to the "new system scientist".
    First, researchers might not have time to so this.
    There is really no incentive for this in the current system.
    Second, researchers definitely don't want to get scooped.
    There is already hesitancy with sharing data, there would be even more hesitancy with sharing system specific knowledge ins a synthesized and digestable form.
    Again, what incentives are there for some new researchers to ask questions in "your system", with "your data", using "your synthesized knowledge".
    I expect that this would get a lot of push back.

-   In reality, would anybody do this?
    Does it offer a significant boost in efficiency than some "new" scientist just trying to synthesize and develop a conceptual model from published literature without ever contacting the "system expert"?
    This option certainly saves the establishing system expert time.
    <!--# See comments above about benefits of open system for an established research group as well as new researchers from outside of a research group. -->

-   In addition, this information system is not static!
    Even after a big initial investment from the systems expert the idea is that the conceptual model would be continually updated.
    This requires effort, incentive, and desire to do this.

-   In some ways, one extreme of this approach to completely remove the "system expert" as a gateway to generative research in a system (i.e., I could ask and answer a cool new question in MYL frogs systems without ever talking to Roland or setting foot in the system).
    Seems terrible when framed like that, but I think that is one extreme of this viewpoint.
    Is that desirable or even possible?
    In some ways, I don't think it is possible.
    Observing a system for yourself vs. digesting someone's conceptual model of a system are very different.
    If this extreme is not feasible, what then is the goal?
    <!--# Again, a primary goal is describing the current state of knowledge, for use by a system's established reseachers and interested outside parties. -->

**Thought experiment on why this is or isn't useful**

### Some relevant papers

*Baker et al. 2007*, *Journal of Intelligent Information Systems*

-   Relevant paper summarizing the challenges the LTERs face when sustaining long-term datasets, facilitating comparisons between datasets, and producing knowledge from data.

-   A couple useful concepts: Information systems, information ecology, the "middleware" (people, software, widgets that are needed to make disparate sets of knowledge/data interoperable).

Good quotes from Baker et al. 2007

-   *It is essentially an altruistic act in a highly competitive world for a scientist to take the time to make their data usable by someone else; particularly when they do not necessarily anticipate any return on their investment in terms of reusable data from elsewhere*

-   *‘how do we build an open information environment?’—a purposefully leaky, data-diverse, tension-balancing information ecology that recognizes uncertainty and facilitates change.*

-   *An information environment isn’t something you finish, it is something you start*

## Tom's thoughts

### Sierra frogs+disease as modeling open system

-   How have we arrived at this discussion?

    Does the work that began with Roland, pulled in Cherie, Vance, and Bree, then Tom, Mark, Max, now Allie, Sam, John/Kira examplify the simultaneous opportunity and challenge of being an open system?

    How many "failed" entrants into this system have there been?
    In other words, how many researchers have earnestly tried to work in the system and been stymied or rebuffed?
    Have important results been missed as a result of non-openness?

-   I believe an incentive is that last point: a non-open system may become siloed, biased, and self-reinforcing.
    And, ahem, "elitist".

-   Is an open system an imperative of making science more open, accessible, and diverse?

    <!--# I would argue that "transparency" is a key benefit of an open system. This hasn't been mentioned specifically in our thoughts, but it brings together benefits conferred to the system's established researchers as well as outside researchers. -->

-   The LTERs seem a very useful case study.
    By their nature, LTERs must create a way to pass questions, knowledge and data, infrastructure between generations of researchers.
    Many systems are effective if not so-called LTERs.
    Other long-term studies have ended with the careers of their PIs (I know one example).

-   Open systems are already functioning and widespread, although each 'system' may exist at a small(er) scale: labs that incorporate graduate students, and LTERs.

-   People with experience in LTERs: Cherie, Carol, Sally McIntyre.
    Cherie might be interesting to get a perspective from, because of her transition (as I percieve it) into the Moorea LTER as a person who came to a system rich in data.
    Carol has been on the SBC LTER for a long time, more on the empirical side.
    Obviously, lots of people we don't know personally at other LTERs and long term studies.

## Roland's thoughts

See my comments inserted above.
