---
title: "Meeting Notes"
author: "Roland Knapp, Tom Smith, Mark Wilber"
format: html
editor: visual
---

## MEETING NOTES and HOMEWORK

### November 6, 2023

-   We restarted our discussion from 5 months ago regarding the structure of the conceptual model, how the model would be used, and what the products of this effort would be.

-   General consensus was to start diagramming a MYL frog conceptual model and use that process to help us to decide on model structure, products, etc.

-   Mark provided several papers that would be useful for us to read, one of which develops a conceptual model for amphibians in the US Midwest.

### Next steps

-   Search for papers that have developed similar conceptual models. Key search terms might be "adaptive management", "decision analysis". Add to repo folder.

-   Read papers in mylfrog_conceptual_model repo for discussion during our next meeting.

-   Before the next meeting, each of us will sketch out what a conceptual model for MYL frogs might look like.

### April  9, 2024

-   Attendance: Mark, Tom

-   revisit "F.L.A.M.E." model idea: Four lifestage amphibian model with environment.

-   Used 10 minutes to execute homework assignment from last meeting: brainstorm 2-3 questions each that motivate the creation and use of a conceptual model for mountain yellow-legged frogs.

    -   Tom's:

    -   <div>

        1.  what processes affect frog population trends that we *are not* addressing but *are feasible* to study?
        2.  are some recovery tools better suited to address the ways that recruitment/survival affect declines/recovery?
        3.  can we determine processes or variables that make winter "matter" to frog survival?

        </div>

    -   Mark's:

    -   <div>

        1.  What can we learn about broad ecological questions (resilience, extremes?)
        2.  How can we leverage extensive data and natural history knowledge of MYL frog science?
        3.  With regard to viability model, can we identify how to incorporate environmental variability into frog viability?

        </div>

-   Reflecting on our answers:

    -   Convergence between Mark and Tom's questions on some topics and themes. Collectively our answers have themes of project/research "administration" (or teaching), conservation/application, and "basic" science.

-   Products?

    -   Synthesis of frog ecology (biology) and management story of 40 years and "100" publications. \[Tom's note: 100 was a Tom and Mark guess, but Google Scholar returns 3600 results for "Rana muscosa\].

        -   A mere review is unpalatable to us, and not as useful as a synthesis or model.

    -   Are we building the mountain yellow-legged frog "canon"?

-   **HOMEWORK for 4/16:**

    -   Think about products we want, or that the world would want, that the CM supports (manusripts, teaching tools).

    -   Take the FLAME model figure <!--@mqwilber: can you add the figure here?-->, and annotate according to three themes. Do different parts of the model apply to these themes differently, or, do these themes demand that we do certain things with the model?

        -   Administration (project guidance, teaching)

        -   Application (conservation)

        -   Research

    -   Other considerations:

        -   Consider the different areas of biology that we are less familiar with and would need literature or input to improve our model (e.g. immunology, physiology... )

        -   Consider geographic and taxonomic scope - include/consider southern CA R. muscosa?
